name: CD to Fly.io
on: 
  push:
    branches: 
      - main

jobs: 
  build-image: 
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
      
      - name: Push image to DockerHub
        uses: docker/build-push-action@v5
        with: 
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/todo-list-be:latest


  deploy: 
    name: deploy
    runs-on: ubuntu-22.04
    needs: build-image
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Set Fly.io Secrets
        run: |
          flyctl secrets set GG_CLIENT_ID=${{ secrets.GG_CLIENT_ID }} -a todo-list-be
          flyctl secrets set GG_CLIENT_SECRET=${{ secrets.GG_CLIENT_SECRET }} -a todo-list-be
          flyctl secrets set GG_REDIRECT_URL=${{ secrets.GG_REDIRECT_URL }} -a todo-list-be 
          flyctl secrets set GG_AUTH_URL=${{ secrets.GG_AUTH_URL }} -a todo-list-be
          flyctl secrets set GG_TOKEN_URL=${{ secrets.GG_TOKEN_URL }} -a todo-list-be
          flyctl secrets set SERVER_PORT=${{ secrets.SERVER_PORT }} -a todo-list-be
        env: 
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Fly.io
        env: 
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: "flyctl deploy --remote-only -a todo-list-be --image ${{secrets.DOCKER_USERNAME}}/todo-list-be:latest"

      
            
